name = "Forge Everything"
author = "Forge Everything Team"
version = "0.0.1-Alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8bd9f952737dcfdba7276d5ae041cc91a103487173f17f5e6e70f18575f456a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
