name = "Forge Everything"
author = "Forge Everything Team"
version = "0.0.1-Alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06f7721cace72b19a1a5badae9f4562ae26285c08ca216c72db9d204eeb28087"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
