name = "Forge Everything"
author = "Forge Everything Team"
version = "0.0.1-Alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f502b5209f22ab72db0ba432bd2a5d41decbd6b7f2c334fdada960c1c6ee760"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
